### ISSUE TITLE
BUG: State not bind to form

### ISSUE THREAD

**Issue by mufeng510** [worktile/store#119]
我使用了 `thyStoreForm `将表单与状态绑定，form 到 state 的变更是正确的，state同步到form出现了故障。看起来在指令中缺少了这部分代码。
预期：状态变更后更新表单值
实际：状态变更后表单未变化
![image](https://github.com/worktile/store/assets/30998460/5de7721b-d125-4b21-9ad0-d485991093f0)

**Comment by why520crazy** [comment]
这个功能还未完全支持，具体看#81
