### ISSUE TITLE
只有 activeId 变化时才能触发 activeEntity$，是否优化为 activeEntity 中任一属性变化时都能触发

### ISSUE THREAD

**Issue by Guoxiin** [worktile/store#123]
目前只有 activeId 变化时才能触发 activeEntity$ ，希望 activeEntity 中任一属性变化时都能触发 activeEntity$ 

1. 如果认为 activeEntity 和 activeId 一样，只在 activeId 变化时触发，只不过 activeEntity 能直接拿到整个实体，好像也没问题
2.  activeEntity 内其他属性变化了，实际 activeEntity 是变化了的，但是 activeEntity$ 订阅不到，只能通过订阅 entities$ 才能知道 activeEntity 变化了，又感觉有点奇怪

**Comment by why520crazy** [comment]
可以这样处理
