### ISSUE TITLE
建议增加一个新的一次性的observable，用于接收某一次store更新后的结果

### ISSUE THREAD

**Issue by 791045873** [worktile/store#58]
在我的业务中出现了这样一个需求。

我监听了entities$用于更新一个表格的数据。（表格使用了aggrid）
但是，由于aggrid会自己维护数据的状态。例如某行被选中，某行被展开（如果数据分组的话）。所以我不能每当数据改变时都用新数据渲染表格，这样会造成表格状态的丢失，而且这个状态我也没法放到store中自己维护。

所以我仅仅当数据源完全切换时，才重新渲染表格。即用订阅到的数据重新渲染。

举例：
我有一个下拉列表用于选中不同的城市，每个城市下存在不同的项目。
````
selectCity = new FormControl('')

selectCity.valueChanges.pipe(switchMap(city => {
   this.projectStore.fetchProjectList(city)
   return this.projectStore.entities$.pipe(take(1))
)
.pipe(takeUntil(this.destory$)).subscribe(data => {
    table.setData(data)
})
````

只有在selectCity的值改变后我才需要用订阅到的entities去渲染表格。但是由于store是BehaviorSubject，会在订阅时直接emit上一次的值，所以我不一定能够拿到由selectCity触发的更新后的数据。如果fetch数据是同步的，可以拿到最新值。如果fetch是异步的，第一次拿到的值是缓存，第二次才是新值。但是我的业务需要又让我不能够一直订阅entities$流。

期望：
希望能够在store这个基类里提供一个一次性的waitForUpdatedStore的Observable。每当我fetch数据时，可以通过传参数激活它，只能订阅一次。结束后即销毁。每次emit当前这次store更新后的值。

如果觉得可行，我想提个pr解决这个问题

**Comment by why520crazy** [comment]
我没有太明白你描述具体的问题，按理说 entities$ 的数据改变是不关心是 fetch 的还是其他操作导致改变的。你是否可以自己通过 selectCity 的流和 entities$ 组合实现你的需求呢？

**Comment by 791045873** [comment]
> 我没有太明白你描述具体的问题，按理说 entities$ 的数据改变是不关心是 fetch 的还是其他操作导致改变的。你是否可以自己通过 selectCity 的流和 entities$ 组合实现你的需求呢？

可以通过组合流实现。
````
selectCity.valueChange.subscribe(city => {
    // 必须得在fetch数据之前订阅这个流，而且还得跳过订阅后由behaviorSubject发出的缓存值。所以得take(2), last()
    this.store.entities$.pipe(take(2), last()).subscribe(data => {
        this.setTableData(data)
    })
    this.store.fetchData(city)
})
````

就是感觉有点麻烦，这样的组合语义不直观。
