### ISSUE TITLE
public StoreFactory and add getStores(names: string | string[])

### ISSUE THREAD

**Issue by why520crazy** [worktile/store#69]
- public StoreFactory
- add `getStores(names: string | string[])` get stores by names
-  update storeInstancesMap's type from `Map` to `WeakMap`

**Comment by Guoxiin** [comment]
我觉得 storeInstancesMap 不需要使用 WeakMap。`private storeInstancesMap = new Map<string, Store>(); `目前 storeInstancesMap 是 id 做 key 的，不存在引用对象、垃圾回收不掉的情况，这个位置是有新需求，需要使用某个对象做 key 吗

**Comment by Guoxiin** [comment]
#79
